""" Joint class """

import numpy as np


class Joint(object):
    """ This class implements the Joint instance for the musculo-skeletal
    system.
    """

    def __init__(self, joint_pos, parameters):
        """This function initializes the joint."""
        # Joint current angular position
        self.joint_pos = joint_pos
        # Joint Torque
        self.torque = 0.0
        # Torque generated by the joint limits
        self.torque_soft_limit = 0.0
        # Ligament stiffness
        self.soft_limit_stiffness = 0.00066
        # Joint velocity
        self.joint_vel = 0.0
        # Maximum joint angle
        self.angle_max = np.deg2rad(
            parameters.theta_max)
        # Minimum joint angle
        self.angle_min = np.deg2rad(
            parameters.theta_min)
        # Angle reference/offset
        self.reference_angle = np.deg2rad(
            parameters.reference_angle)
        # New Joint angle
        self.new_angle = 0.0
        # Previous Joint angle
        self.prev_angle = 0.0
        # Either CONSTANT or GEYER
        self.joint_type = parameters.joint_type
        # Joint name
        self.name = parameters.name

    def getAngle(self):
        """Function returns the current angle of the joint."""
        return self.joint_pos

    def updateAngle(self, angle):
        """Function updates the joint angle.

        Parameters
        ----------
        angle: float
            Joint angle
        """
        self.joint_pos = angle

    def step(self, dt=0.001):
        """ This function updates the joint instance."""
        self.new_angle = self.getAngle()
        self.d_angle = (self.new_angle - self.prev_angle) / dt
        self.prev_angle = self.new_angle
        self.torque = 0.0

    def AddForce(self, torque):
        """ Add torque to the joint.

        Parameters
        ----------
        torque: float
            Muscle torque applied on to the joint
        """
        self.torque += torque

    def ComputeTorqueSoftLimit(self, dt=0.001):
        """ This function computes the torque generated by the ligaments in
        the joint.
        """
        flag = (dt * 1000)
        force_ratio = 0.001
        n_vLim = 1.0 * 0.0175

        if self.joint_pos < self.angle_min:
            self.torque_soft_limit = self.soft_limit_stiffness / flag * \
                (self.joint_pos - self.angle_min) * \
                (1.0 - self.d_angle / n_vLim / flag)
        elif self.joint_pos > self.angle_max:
            self.torque_soft_limit = self.soft_limit_stiffness / flag * \
                (self.joint_pos - self.angle_max) * \
                (1.0 + self.d_angle / n_vLim / flag)
        else:
            self.torque_soft_limit = 0.0

        self.torque_soft_limit *= force_ratio

    def ComputeTorque(self):
        """Function computes the net joint torque."""
        self.torque = self.torque - self.torque_soft_limit

    def getTorque(self):
        """Function returns the torque."""
        return self.torque

    def getName(self):
        """Function returns the name of the joint."""
        return self.joint_name
